### ISSUE TITLE
Messages spamming console in production

### ISSUE THREAD

**Issue by darkhax** [lospec/Procedural-Pixel-Art-Generator#3]
There are a few issues with spamming the console with data. The main issue is that each log call will increase the memory used by the browser for your page. In this site you are printing lots of data when generating the sprites, which will start building up after long use. Console logging also has a very small hit to the performance of the script, however the performance hits add up when there are many of them. 

I would suggest removing some of the debug messages from commonly executed code, or replacing the console code with some form of logging system that can be turned off when not debugging the page.

**Comment by lospec** [comment]
You were right, this was due to a recent update to my gulp file, in which I forgot to reenable uglify in, should be fixed now (and on all other pages as well)
